name             'lamp'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures lamp'
long_description 'Installs/Configures lamp'
version          '0.1.0'
recipe 'lamp', 'Main Apache configuration'

depends 'apache2', '~> 3.0.0'
depends 'mysql', '~> 6.0'